### ISSUE TITLE
cloud-config tutorial is not working

### ISSUE THREAD

**Issue by pascalandy** [digitalocean/do_user_scripts#58]
I followed this tutorial over: https://www.digitalocean.com/community/tutorials/how-to-use-cloud-config-for-your-initial-server-setup

Then I copy-paste this guy in `User Data`, (updated the ssh-key) and tried it ...

```
#cloud-config
users:
  - name: demo
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCv60WjxoM39LgPDbiW7ne3gu18q0NIVv0RE6rDLNal1quXZ3nqAlANpl5qmhDQ+GS/sOtygSG4/9aiOA4vXO54k1mHWL2irjuB9XbXr00+44vSd2q/vtXdGXhdSMTf4/XK17fjKSG/9y3yD6nml6q9XgQxx9Vf/IkaKdlK0hbC1ds0+8h83PTb9dF3L7hf3Ch/ghvj5++tWJFdFeG+VI7EDuKNA4zL8C5FdYYWFA88YAmM8ndjA5qCjZXIIeZvZ/z9Kpy6DL0QZ8T3NsxRKapEU3nyiIuEAmn8fbnosWcsovw0IS1Hz6HsjYo4bu/gA82LWt3sdRUBZ/7ZsVD3ELip user@example.com
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
runcmd:
  - sed -i -e '/^Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
```

but ... nothing !?

I'm using the docker image 1.12.1

--- 

It would be VERY nice to have updated cloud-inits over Github the way http://cloudinit.readthedocs.io/en/latest/topics/examples.html is doing it. 

This is need for serious cloud operation. 
Cheers!
